import math

FRAME_PER_SECONDS = 10
RAY_COUNT = 100
FOV_ANGLE = (math.pi / 3)
PERSON_MOVEMENT_VELOCITY = 5 / FRAME_PER_SECONDS
PERSON_TURN_VELOCITY = math.pi / FRAME_PER_SECONDS
DOOR_OPEN_VELOCITY = round(2 / FRAME_PER_SECONDS, 1)
DOOR_INTERVAL_CLOSE = round(1 / FRAME_PER_SECONDS, 1)
