name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Configura o Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Executar testes
        run: |
          python -m pytest --cov --cov-report xml
      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml,./coverage2.xml # optional
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)